//post reducer  
export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_RANGE = "SET_POSTS_RANGE";
export const SET_SEARCH_POSTS = "SET_SEARCH_POSTS";
export const ADD_LIKED_POST = "ADD_LIKED_POST";
export const DELETE_LIKED_POST = "DELETE_LIKED_POST";
export const ADD_COMMENT_POST = "ADD_COMMENT_POST";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const IDENTIFY_THE_SELECTED_POST = "IDENTIFY_THE_SELECTED_POST";
export const SET_SEARCH_INPUT_VALUE = "SET_SEARCH_INPUT_VALUE";
export const PAGE_VIEW_SWITCH = "PAGE_VIEW_SWITCH";
export const CHANGE_AMOUNT_VISIBLE_ITEMS = "CHANGE_AMOUNT_VISIBLE_ITEMS";
export const IS_TIME_REQUEST = "IS_TIME_REQUEST";
export const RAISES_CURRENT_PAGE = "RAISES_CURRENT_PAGE";
export const CHANGE_ORDER_ITEMS = "CHANGE_ORDER_ITEMS";
export const ACTIVE_CONTENT_PAGE = "ACTIVE_CONTENT_PAGE";
export const INPUT_VALUE = "INPUT_VALUE";

//album reducer  
export const GET_ALBUMS = "GET_ALBUMS";
export const SET_ALBUMS = "SET_ALBUMS";
export const SET_ALBUMS_RANGE = "SET_ALBUMS_RANGE";
export const ADD_LIKED_ALBUM = "ADD_LIKED_ALBUM";
export const DELETE_LIKED_ALBUM = "DELETE_LIKED_ALBUM";
export const SET_SEARCH_INPUT_VALUE_ALBUMS = "SET_SEARCH_INPUT_VALUE_ALBUMS";
export const CHANGE_CURRENT_PAGE_ALBUMS = "CHANGE_CURRENT_PAGE_ALBUMS";
export const CHANGE_ORDER_ITEMS_ALBUMS = "CHANGE_ORDER_ITEMS_ALBUMS";
export const CHANGE_AMOUNT_VISIBLE_ITEMS_ALBUMS = "CHANGE_AMOUNT_VISIBLE_ITEMS_ALBUMS";
export const PAGE_VIEW_SWITCH_ALBUMS = "PAGE_VIEW_SWITCH_ALBUMS";
export const RAISES_CURRENT_PAGE_ALBUMS = "RAISES_CURRENT_PAGE_ALBUMS";